'use strict';
const assert=require('node:assert/strict'),Storage=require('../../public/roster-storage.js'),{harness}=require('./mobile_harness.cjs');
const staff=[{id:'a',name:'旧名A',type:'full',nightShiftType:'all',monthlyDaysOff:9,canOvertime:true},{id:'b',name:'職員B',type:'full',nightShiftType:'all',monthlyDaysOff:9}];
const shifts=Object.fromEntries(['early','late','night','nightOff','off','overtime','part'].map(v=>[v,v]));
const row=Object.fromEntries(Array.from({length:30},(_,i)=>[String(i+1),'off']));row['30']='night';
const manual=['off','off','off','off','off','off','nightOff'];
const raw={staff,schedules:{'2026-09':{assignments:{a:row,b:row},requests:{a:[6]},previous:{assignments:{a:{...row,'30':'off'},b:row},locked:{},meta:null}},'2026-10':{assignments:{a:{'1':'off'}},requests:{a:[7]},history:{a:manual},locked:{a:{'8':'early'}}}},preferences:{maxExtraOffSpread:1,staffing:{requiredStaff:[4,4,4],maxReducedSundays:3}}};
const clone=x=>JSON.parse(JSON.stringify(x));
(async()=>{
 const h=harness(raw);assert.equal(h.get('state.loadError'),false);assert.equal(h.get('data.savedTables.length'),3);
 assert.equal(h.get('hasTable()'),false);assert.deepEqual(h.get('history().a'),manual);assert.equal(h.get('history().b[6]'),'night');
 assert.equal(h.values.get('koukyu_v3_data'),JSON.stringify(raw));assert(h.values.has('koukyu_v4_data'));
 const migrated=h.get('data.savedTables');assert.deepEqual(migrated[0].schedule.assignments.a,row);
 h.eval("data.schedules['2026-10'].assignments={a:{'1':'off'},b:{'1':'off'}};schedule().workSignature=inputData().signature;schedule().meta={status:'FEASIBLE',boundaryComplete:true};");
 h.eval('saveTableDialog()');await h.click('保存する');h.eval('saveTableDialog()');await h.click('保存する');
 assert.equal(h.get('data.savedTables.length'),5);const saved=h.get('data.savedTables.at(-1)');
 const disk=JSON.parse(h.values.get('koukyu_v4_data'));assert.deepEqual(disk.schedules['2026-10'].assignments,{});assert.equal(disk.savedTables.length,5);
 assert.deepEqual(disk.schedules['2026-10'].history.a,manual);assert.deepEqual(disk.schedules['2026-10'].locked,{a:{'8':'early'}});
 h.eval("data.staff[0].name='新名A';data.preferences.staffing.requiredStaff=[0,0,0];render();");
 assert.equal(h.get('hasTable()'),true);assert(h.get('workChanged()'));assert.deepEqual(h.get('data.savedTables.at(-1)'),saved);assert.deepEqual(h.get('history().a'),manual);
 h.eval('state.tab="saved";state.archiveId=data.savedTables.at(-1).id;render();');
 assert(h.nodes.view.text.includes('旧名A'));assert(!h.nodes.view.text.includes('新名A'));assert(h.nodes.view.text.includes('必要人数：朝4人'));
 assert(!h.nodes.view.text.includes('現在の条件と合わない'));assert.equal(h.calls.length,0);assert.equal(h.timers.length,2);
 const restored=harness(null,{current:disk});assert.equal(restored.get('hasTable()'),false);assert.equal(restored.get('data.savedTables.length'),5);assert.deepEqual(restored.get('history().a'),manual);
 const roundtrip=h.get('checkBackup(RosterStorage.persisted(data))');assert.equal(roundtrip.savedTables.length,5);
 const bad=clone(disk);bad.savedTables[1].id=bad.savedTables[0].id;assert.throws(()=>h.ctx.checkBackup(bad));
 const missing=clone(disk);delete missing.savedTables;assert.throws(()=>h.ctx.checkBackup(missing));
 const snapshot=clone(disk.savedTables[0]);const imported=Storage.takeHistory(snapshot,'2026-10',staff,{a:manual},shifts);assert.deepEqual(imported.history.a,manual);assert.equal(imported.added,1);assert.equal(imported.history.b[6],'night');
 assert.throws(()=>Storage.takeHistory(snapshot,'2026-11',staff,{},shifts));
 const quota=harness(raw,{quota:true});assert.equal(quota.values.has('koukyu_v4_data'),false);assert.equal(quota.values.get('koukyu_v3_data'),JSON.stringify(raw));
 quota.eval("schedule().assignments={a:{'1':'off'}};schedule().workSignature=inputData().signature;saveTableDialog();");const before=quota.get('data.savedTables.length');await quota.click('保存する');assert.equal(quota.get('data.savedTables.length'),before);
 quota.eval('deleteSavedTable(data.savedTables[0].id)');assert.equal(quota.get('data.savedTables.length'),before);
 const id=h.get('data.savedTables.at(-1).id');h.eval('deleteSavedTable('+JSON.stringify(id)+')');assert.equal(h.get('data.savedTables.length'),4);assert.equal(JSON.parse(h.values.get('koukyu_v4_data')).savedTables.length,4);
 const draft=harness(raw,{response:async payload=>payload.action==='validate'?{status:'VALID',validationErrors:[],boundaryComplete:true}:{status:'DRAFT',assignments:{s0:{'1':'early'},s1:{'1':'off'}},unmetConditions:[{code:'coverage',day:1,time:420,actual:1,required:4}],boundaryComplete:true,optimizationPolicy:'quality-first-1'}});
 draft.eval("schedule().assignments={a:{'1':'off'},b:{'1':'off'}};schedule().workSignature=inputData().signature;schedule().meta={status:'DRAFT',unmetConditions:[],boundaryComplete:true};");
 const archives=draft.get('data.savedTables');await draft.ctx.generate(15);assert.equal(draft.calls[0].initialAssignments,undefined);assert.equal(draft.calls[0].adaptive,false);
 assert.equal(draft.get("schedule().assignments.a['1']"),'early');assert.deepEqual(draft.get('data.savedTables'),archives);assert.deepEqual(draft.get('history().a'),manual);assert.equal(draft.confirmations.length,0);
 await draft.ctx.generate(60);assert(draft.calls[1].initialAssignments);assert.equal(draft.calls[1].adaptive,false);assert.deepEqual(draft.calls[1].input.locked.s0,{'8':'early'});
 const failed=harness(raw);failed.eval("schedule().assignments={a:{'1':'off'}};schedule().workSignature=inputData().signature;schedule().meta={status:'FEASIBLE'};");await failed.ctx.generate(15);assert.equal(failed.get('hasTable()'),true);assert.equal(failed.get('data.savedTables.length'),3);assert(failed.nodes.notice.textContent.includes('元の表'));
 const editing=harness(raw,{response:async()=>({status:'VALID',validationErrors:[],boundaryComplete:true})});
 editing.eval("schedule().assignments={a:{'1':'off'},b:{'1':'off'}};schedule().workSignature=inputData().signature;editShift(data.staff[0],1);");
 const fixed=editing.nodes['dialog-body'].all('input').find(e=>e.type==='checkbox');assert.equal(fixed.checked,false);
 await editing.click('変更を反映');assert.equal(editing.calls[0].action,'validate');assert.deepEqual(editing.get('history().a'),manual);assert.equal(JSON.parse(editing.values.get('koukyu_v4_data')).schedules['2026-10'].assignments.a,undefined);
 editing.eval("copySavedTableDialog(data.savedTables[0]);");const originals=editing.get('data.savedTables');await editing.click('編集用のコピーを作る');assert.deepEqual(editing.get('data.savedTables'),originals);assert.equal(editing.get('hasTable()'),true);
 const entry=harness(raw);entry.eval('editHistory()');const selects=entry.nodes['dialog-body'].all('select');const last=selects.at(-1);last.value='night';last.onchange();await entry.click('入力した勤務を保存');
 assert.equal(entry.get('history().a[6]'),'night');await entry.ctx.generate(15);assert.equal(entry.calls[0].input.history.s0[6],'night');assert.equal(entry.get('history().a[6]'),'night');
 const exported=JSON.parse(await entry.ctx.backupFile().text());assert.deepEqual(exported.schedules['2026-10'].assignments,{});assert.equal(exported.schedules['2026-10'].history.a[6],'night');assert.equal(exported.savedTables.length,3);
 const loading=harness();await loading.nodes.import.onchange({target:{files:[{size:100,text:async()=>JSON.stringify(exported)}],value:'backup'}});assert.equal(loading.get('data.savedTables.length'),3);assert.equal(loading.get('history().a[6]'),'night');assert.equal(loading.get('hasTable()'),false);
 const broken=clone(disk);broken.schedules['2026-10'].history={a:['wrong']};assert.throws(()=>h.ctx.checkBackup(broken));
 const crowded=harness(raw);crowded.eval("data.staff=Array.from({length:40},(_,i)=>({id:'other'+i,name:'職員'+i,type:'full',nightShiftType:'none'}));copySavedTableDialog(data.savedTables[0]);");const registry=crowded.get('data.staff');await crowded.click('編集用のコピーを作る');assert.deepEqual(crowded.get('data.staff'),registry);assert(crowded.nodes['dialog-body'].text.includes('40人を超える'));
 let finish;const race=harness(raw,{response:async()=>new Promise(resolve=>{finish=resolve;})});race.eval("schedule().assignments={a:{'1':'off'},b:{'1':'off'}};schedule().workSignature=inputData().signature;");const pending=race.ctx.validateCurrent();race.ctx.toggleRequest('a',2,'off');finish({status:'VALID',validationErrors:[],boundaryComplete:true});await pending;assert.equal(race.get('hasTable()'),true);assert(race.get('workChanged()'));assert.deepEqual(race.get('history().a'),manual);assert.equal(race.get('data.savedTables.length'),3);
 console.log('PASS: 旧表移行、複数保存、独立閲覧・印刷、条件変更、前期履歴優先、バックアップ、容量不足時の保護、削除、新規/改善、失敗時、編集コピー');
})().catch(e=>{console.error(e);process.exitCode=1;});
